### ISSUE TITLE
报错提示

### ISSUE THREAD

**Issue by arvinyu** [largezhou/admin#1]
$ php artisan jwt:sectet
In ProviderRepository.php line 208:
  Class 'Overtrue\LaravelLang\TranslationServiceProvider' not found

**Comment by largezhou** [comment]
你，，，`Laravel` 那一套流程走了吗，，，

**Comment by arvinyu** [comment]
找到原因了，是因为打包下来的代码不包含vendor包，我composer了一下就可以了

**Comment by arvinyu** [comment]
不过有另外一个问题，数据库表示在什么时间创建的？建表语句在哪找？
