### ISSUE TITLE
修改代码后不生效

### ISSUE THREAD

**Issue by zhangweixi** [largezhou/admin#10]
修改代码后，watch是监控到修改了的，但是浏览器自动刷新后，页面并没有变化，这个问题经常出现

**Comment by zhangweixi** [comment]
发现是缓存造成的，可不可以刷新的时候都获取最新的呀，资源路径可以加随机数吗

**Comment by largezhou** [comment]
> 发现是缓存造成的，可不可以刷新的时候都获取最新的呀，资源路径可以加随机数吗

默认情况下，开发环境，生成的资源不会带哈希码，所以需要打开控制台的“disable cache”，才能看到刷新后的效果。

生产环境生成的资源都是带哈希码的，就不需要强制刷新。

在 vue.config.js 中适当位置加上 `config.output.filename('[name].[hash].js').end()`
