### ISSUE TITLE
本地 run serve的时候  请求后台域名 貌似host 问题不携带 cookie

### ISSUE THREAD

**Issue by Axierty** [largezhou/admin#11]
本地  run serve 启动 vue 登录有个提示 messages 未定义 

很奇怪 不过此处很好解决 改一些utils 就好
export const getMessage = key => {
  /* eslint-disable no-undef */
 //  return messages[key] || messages.default   ide 都可以追到 messages 这个变量 但console提示找不到
  console.log(key)
  return key
}

调整完毕以后 
请求后台接口 时貌似因为前段域名 localhost , 接口域名 xxx.com 就没有携带cookie 就一直401 走不通了 ，不能本地调试 那开发就太费劲了

**Comment by largezhou** [comment]
前端不是用 serve 这种模式的，，，请看文档 nginx 部分

**Comment by Axierty** [comment]
> 前端不是用 serve 这种模式的，，，按照文档来

文档那种是打包编译以后，就是调试开发阶段 每次改了东西都需要打包还是比较慢的。一般自动编译和热更新 这种就方便开发一些，随时改 随时更新 适合debug 。

**Comment by Axierty** [comment]
> 前端不是用 serve 这种模式的，，，按照文档来

--watch  参数就是监测文件变动自动编译的  vue 不太熟 知道了 这个也很方便
