### ISSUE TITLE
前端面包屑组件, 逻辑问题

### ISSUE THREAD

**Issue by carl-jin** [largezhou/admin#16]
# 版本

作者还未提供版本号

# BUG 复现地址

无

# 复现步骤

```javascript
let matchedRouter = [
  {
    id: "a",
    title: "a-分类",
    path: "/a/"
  },
  {
    id: "b",
    title: "a-b分类",
    path: "/a/b/"
  }
];
this.$store.commit("SET_MATCHED_MENUS_CHAIN", matchedRouter);
```

# 预期效果

使用 `SET_MATCHED_MENUS_CHAIN` mutation 更新面包屑, 达到手动更新面包屑效果(自定义面包屑)

# 实际效果

内存溢出
![溢出](https://api.monosnap.com/file/download?id=uDLEsI4BRQOTkE2hgBryLdjzDtZFZp)

# 目测原因

[源代码行数](https://github.com/largezhou/admin/blob/master/resources/admin/src/components/Layout/components/Breadcrumb.vue#L27)

27 行, 与 41 行代码执行时会操作同一个 Array(引用对象),

即使赋值给了变量`m`, 但是实际操作的还是`matchedMenusChain`,

导致, 添加首页后, computed 又进行了一次重新的计算

解决方法也比较简单 解构下就行

```javascript
[...this.matchedMenusChain];
```

# ?

为何不提交 fork?, 写个 issue 吧, 懒得再提交个 fork 了

**Comment by largezhou** [comment]
，，，有空看下，最近都没空，都没发现有2个 issue，，，

**Comment by largezhou** [comment]
这个面包屑其实挺难搞成自动的，，，

**Comment by largezhou** [comment]
我按照你的复现步骤，没复现出来，，，不过解决办法是可以用，确实应该解构一下
