### ISSUE TITLE
权限的问题

### ISSUE THREAD

**Issue by XinJiangQingMang** [largezhou/admin#2]
如果后台有一组管理叫超级编辑 。他拥有对文章的增删改查。是不是 要单独添加个权限叫超级编辑，然后添加路劲 content/*

再有一个普通编辑  他只能对文章进行增加和编辑  要单独添加个权限普通编辑 ,路劲再添加content/add    content/edit  

还有一个编辑 他只有审核的权限， 再添加一个  路劲 content/audit ?

权限是这样的吗   跟菜单没关系 。权限要添加N个  这种权限好奇怪 

还是我理解有问题

**Comment by largezhou** [comment]
权限不都是每个接口对一个权限吗？

只是这个带了个 * 号通配符，如果某些不用细分的，就可以用通配符，，，

所以你这个 content 权限，如果每个权限都要分开，就没必要 再定义一个 content/* 的权限了，，

**Comment by XinJiangQingMang** [comment]
> 权限不都是每个接口对一个权限吗？
> 
> 只是这个带了个 * 号通配符，如果某些不用细分的，就可以用通配符，，，
> 
> 所以你这个 content 权限，如果每个权限都要分开，就没必要 再定义一个 content/* 的权限了，，

如果细分呢  就是不同角色精准到按钮级  不是页面级

**Comment by XinJiangQingMang** [comment]
或者能不能  路由和权限的路劲关联  让用户去选择 而不是手动输入

**Comment by largezhou** [comment]
1：精确到按钮的话，必须在前端使用我提供的指令来判断按钮的显示与隐藏

2：不能，因为我后台的路由配置，是配置的前端路由，，，并不是后端的，，

我这个跟 `laravel-admin` 扩展是一样的，，，我个人觉得是很合理的，，，

**Comment by XinJiangQingMang** [comment]
刷新页面404 是配置不对吗

**Comment by XinJiangQingMang** [comment]
谢谢
