### ISSUE TITLE
有没有人遇到拉取代码，一系列安装后，登录，即使验证码输入错误，也可以进入系统

### ISSUE THREAD

**Issue by hyhlife** [largezhou/admin#24]

**Comment by largezhou** [comment]
不好意思，没注意有 issues，，，刚才看了下，是验证码扩展 3.2.8 开始，增加了一个 disable 的配置，默认是只要环境不是 `prod` 就为 true，，，略坑，，，我还是看了验证码插件的代码提交记录才看出来问题的，，，

**Comment by largezhou** [comment]
已经加上这个配置了，`.env.example` 中 `CAPTCHA_DISABLE=false`。感觉还是要锁一下包版本，，，
