### ISSUE TITLE
请问安装的流程能不能详细点啊

### ISSUE THREAD

**Issue by lxge** [largezhou/admin#5]
我用laravel new admin 然后在里面执行php artisan jwt:secret这个吗?
我执行了会报错的, There are no commands defined in the "jwt" namespace.
安装的流程能给我详细说一下吗

**Comment by opwish** [comment]
要在项目根目录执行
- composer install
- cp .env.example .env（自己修改环境变量）
- php artisan migrate
- php artisan jwt:secret

**Comment by lxge** [comment]
> 要在项目根目录执行
> 
> * composer install
> * cp .env.example .env（自己修改环境变量）
> * php artisan migrate
> * php artisan jwt:secret

恩 谢谢 昨天我也是跟着这样弄的,有开发文档吗,怎么进行修改啊,直接看不大看得懂

**Comment by largezhou** [comment]
> 要在项目根目录执行
> 
> * composer install
> * cp .env.example .env（自己修改环境变量）
> * php artisan migrate
> * php artisan jwt:secret

我几次想进来写详细点，，，但是我又想跟这位童鞋说，建议他去先了解下 laravel，，，但最后我都没写，，

而这次进来，我是确定要写的，，发现你写了，，，

**Comment by largezhou** [comment]
> > 要在项目根目录执行
> > 
> > * composer install
> > * cp .env.example .env（自己修改环境变量）
> > * php artisan migrate
> > * php artisan jwt:secret
> 
> 恩 谢谢 昨天我也是跟着这样弄的,有开发文档吗,怎么进行修改啊,直接看不大看得懂

开发文档可能木有额，，，还是建议你先学习下 laravel 和 vue，这个不适合新手二开的~~~

**Comment by lxge** [comment]
> > > 要在项目根目录执行
> > > 
> > > * composer install
> > > * cp .env.example .env（自己修改环境变量）
> > > * php artisan migrate
> > > * php artisan jwt:secret
> > 
> > 
> > 恩 谢谢 昨天我也是跟着这样弄的,有开发文档吗,怎么进行修改啊,直接看不大看得懂
> 
> 开发文档可能木有额，，，没啥特殊的规定，最多也就后端封装了几个简单的方法，看看原来的代码，就可以照着用了。
> 
> 还有就是前端封装了一些组件，也是看看，就可以照着用了~~~
> 
> 还是建议你先学习下 laravel 和 vue，，

嗯 好的 谢谢你的建议,我自己多看看;在请教一下,请问怎么打包成很多chunkjs的啊,在其他地方也看到过

**Comment by largezhou** [comment]
yarn build 就会生成那种文件，，，

**Comment by lxge** [comment]
> yarn build 就会生成那种文件，，，

了解,谢谢啦
